# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0002_auto_20180512_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'f1e42f64-86e6-4a1f-8bc9-1ac80a4a270c', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 13, 24, 1, 980007)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 13, 24, 1, 979516)),
        ),
    ]
